dependencies:
- name: mongodb
  version: 7.4.0
  repository: https://kubernetes-charts.storage.googleapis.com
- name: redis
  version: 9.3.0
  repository: https://kubernetes-charts.storage.googleapis.com