dependencies:
- name: mongodb
  version: 7.8.1
  repository: https://kubernetes-charts.storage.googleapis.com
- name: redis
  version: 10.4.0
  repository: https://kubernetes-charts.storage.googleapis.com